import Link from 'next/link';
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/card";
import { News } from '@/types/news';
import { format } from 'date-fns';
import { ja } from 'date-fns/locale';
import { Badge } from "@/components/ui/badge";

interface NewsCardProps {
  news: News;
}

export function NewsCard({ news }: NewsCardProps) {
  // 日付フォーマット
  const formattedDate = format(new Date(news.publishedAt), 'yyyy年M月d日', { locale: ja });

  // 自動生成記事かどうかをチェック
  const isAutoGenerated = news.source === 'AI News Bot';
  
  return (
    <Card className="h-full flex flex-col">
      <CardHeader className="pb-2">
        <div className="flex flex-col gap-1">
          <Link href={`/news/${news.id}`} className="font-semibold hover:underline text-lg">
            {news.title}
          </Link>
          <p className="text-muted-foreground text-sm">{formattedDate}</p>
          
          {/* カテゴリとAI生成バッジ */}
          <div className="flex flex-wrap gap-2 mt-1">
            <Badge variant="outline" className="text-xs">
              {news.category}
            </Badge>
            
            {isAutoGenerated && (
              <Badge variant="secondary" className="text-xs bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300">
                AI生成
              </Badge>
            )}
          </div>
        </div>
      </CardHeader>
      <CardContent className="pt-2 pb-4 flex-grow">
        <p className="text-sm text-muted-foreground line-clamp-3">
          {news.description}
        </p>
      </CardContent>
      <CardFooter className="pt-0 text-xs text-muted-foreground flex justify-between">
        <div>出典: {news.source}</div>
        <Link href={`/news/${news.id}`} className="text-blue-600 hover:underline">
          続きを読む
        </Link>
      </CardFooter>
    </Card>
  );
} 